version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

volumes:
  postgres:
