version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_adminer_data:/var/lib/mysql
  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 33060:8080

volumes:
  mysql_adminer_data:
