version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres_pgadmin_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 54320:80
    volumes:
      - pgadmin_files:/var/lib/pgadmin

volumes:
  postgres_pgadmin_data:
  pgadmin_files:
