version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
