version: '3'

volumes:
  redis_data:

services:
  redis:
    image: redis
    command: redis-server --requirepass qwe123*
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    depends_on:
      - redis
